### ISSUE TITLE
Error: use of unstable library feature 'string_split_off' when trying to install with Cargo

### ISSUE THREAD

**Issue by snitko** [sharkdp/fd#86] opened 2017-10-09 10:07 UTC
Trying to install with cargo (Ubuntu 17.04, cargo 0.16.0-nightly) results in the following error:

```
Compiling fd-find v4.0.0
error: use of unstable library feature 'string_split_off' (see issue #38080)
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/fd-find-4.0.0/src/lscolors/mod.rs:136:63
    |
136 |                         let extension = String::from(pattern).split_off(2);
    |                                                               ^^^^^^^^^

error: use of unstable library feature 'string_split_off' (see issue #38080)
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/fd-find-4.0.0/src/lscolors/mod.rs:140:62
    |
140 |                         let filename = String::from(pattern).split_off(1);
    |                                                              ^^^^^^^^^

error: aborting due to 2 previous errors

error: failed to compile `fd-find v4.0.0`, intermediate artifacts can be found at `/tmp/cargo-install.fPpGpxXFqfNx`
```

**Comment by sharkdp** [comment] 2017-10-09 10:53
Which version of Rust are you using? You will need at least 1.16.

I'm closing this, as it seems to be a duplicate of #43 and #79.

**Closed by sharkdp** 2017-10-09 10:53 UTC
