### ISSUE TITLE
[BUG] --changed-within does not like GNU date output

### ISSUE THREAD

**Issue by eater** [sharkdp/fd#1383] opened 2023-09-10 18:03 UTC
### Checks

- [X] I have read the troubleshooting section and still think this is a bug.

### Describe the bug you encountered:

The `fd` man page says it accepts a "specific point in time in ... full  RFC3339  format  with  time zone."

The `date` man page says it outputs "date/time in RFC 3339 format."

But `fd` won't accept the output of `date`:

```
$ date --reference=.last-sync --rfc-3339=seconds
2023-02-24 11:05:18-05:00

$ fd --changed-within "$(date --reference=.last-sync --rfc-3339=seconds)"
[fd error]: '2023-02-24 11:05:18-05:00' is not a valid date or duration. See 'fd --help'.
```

I'm just a user and I'm not about to read the RFC, but it would be awfully convenient to be able to easily pass datestamps from one tool to the other without converting the format, to achieve a functionality similar to `find -newer`. 

`fd` also doesn't like the output of `stat -c %y .last-sync`, which would be another convenient way to get the last-modified time of a file.

### Describe what you expected to happen:

`fd --changed-within` should accept the output of GNU `date`.

### What version of `fd` are you using?

fd 8.7.0

### Which operating system / distribution are you on?

```shell
Linux 5.19.0-43-generic x86_64
Ubuntu 22.04.3 LTS
```

**Comment by tmccombs** [comment] 2023-09-10 20:24
Hmm, I think the timezone offset might be the problem.

**Comment by tmccombs** [comment] 2023-09-11 06:14
Actually I think the problem is that `date` uses a space separator instead of `T`, on the master branch of `fd`, this actually behaves as expected, probably because it has a newer version of chrono that accepts a space as teh separator.

**Comment by tmccombs** [comment] 2023-10-21 16:22
I believe this is fixed in the latest release.

**Closed by tmccombs** 2023-10-21 16:22 UTC
Labels: bug
