### ISSUE TITLE
environment variable to make e.g. --no-ignore a default?

### ISSUE THREAD

**Issue by luckman212** [sharkdp/fd#1066] opened 2022-07-15 03:33 UTC
version
```
$ fd --version
fd 8.4.0
```

I was wondering if there was any way to set an environment variable or an .fdconfig file etc to add some default flags such as `--no-ignore`? This could be useful.

For now I made a Bash alias
```
alias fd='fd --no-ignore'
```
This works but is crude.

**Comment by tmccombs** [comment] 2022-07-21 04:36
I think this is a duplicate of https://github.com/sharkdp/fd/issues/612 and https://github.com/sharkdp/fd/issues/362. 

Using an alias or a wrapper script is the current recommended way to use this as the default.

**Closed by tmccombs** 2022-07-21 04:36 UTC
Labels: question
