### ISSUE TITLE
find files that match all patterns

### ISSUE THREAD

**Issue by jack99999** [sharkdp/fd#698] opened 2020-12-03 09:15 UTC
locate has this option:

`-A, --all
              Print only entries that match all PATTERNs instead of requiring only one of them to match.`

i have a locate database of my directories and can search for files using an alias of:

` locate -d /home/jack/mylocate.db --all -i` 

is there any equivalent in fd? i haven't spotted a way to do it. if not, would this be a reasonable addition?

**Comment by sharkdp** [comment] 2020-12-06 10:59
duplicate of #650 #414?

**Comment by jack99999** [comment] 2020-12-06 11:53
yes, it's pretty much a duplicate of #650. 

i admit i could do fd 'A.*B|B.*A' but i'd probably just end up using locate instead, if possible.

**Comment by sharkdp** [comment] 2020-12-06 12:05
Ok, please feel free to +1 the other ticket or comment therein

**Closed by sharkdp** 2020-12-06 12:05 UTC
Labels: duplicate, feature-request
