### ISSUE TITLE
sudo rm fd files

### ISSUE THREAD

**Issue by ixzh** [sharkdp/fd#775] opened 2021-06-09 05:53 UTC
**What version of `fd` are you using?*
latest version.

I run `fd -tf -d1 /usr/share/unicode -x sudo rm {} \;` and whole system get removed, similar to 'sudo rm /*' what's wrong here?

A few months back I also run a smiliar `fd -tf -x sudo rm` in some folder under / and the system was damaged beyond repair.

shouldn't it remove only what had been found in the target folder?

**Comment by tmccombs** [comment] 2021-06-09 08:34
that is very strange.

that command shouldn't do anything, because it is searching for the pattern "/usr/share/unicode" in the current directory, which shouldn't match anything unless you also used the `--full-path` option.

**Comment by ixzh** [comment] 2021-06-09 10:59
> that command shouldn't do anything

Sorry, I cd /usr/share/unicode folder first...the command was something like:

`fd -tf -x sudo rm {} \;`

**Comment by sharkdp** [comment] 2021-06-10 11:37
I would definitely not recommend to run `sudo rm` like this. At least use the interactive flag `rm -i`. Or run `… -x echo sudo rm` first to see what's going to be executed (but note that things might have changed when you run the final command).

That being said, it should *not* remove the entire system. It shouldn't even remove any folders because you didn't pass `-r` to `rm`.  Can this be reproduced in a virtual machine?

> *_What version of `fd` are you using?_
> latest version.

so v8.2.1?

**Comment by ixzh** [comment] 2021-06-10 12:39
>  note that things might have changed when you run the final command

yes, fd 8.2.1.Can you explain the statement? Do you mean this command is also not safe? or fd is changing its behavior in future versions that this command might not applicable?

**Comment by ixzh** [comment] 2021-06-10 12:41
Apart from learning what I have done wrong, I'd also like to know  for folders requiring root access how to safely batch remove files as non-root user?

**Comment by sharkdp** [comment] 2021-06-10 12:51
> Can you explain the statement? Do you mean this command is also not safe? or fd is changing its behavior in future versions that this command might not be applicable?

What I meant was: If you use `fd … -x echo something` before running `fd … -x something` to check, then things on the filesystem might have changed between the two runs. So you cannot be 100% sure about the outcome (unless you know that nothing has changed on the filesystem). For `rm`, I would definitely recommend `-i`. Alternatively, pipe the list of filenames to a textfile, manually review it, and then use `xargs` to `rm` all files.

> Apart from learning what I have done wrong

I don't think you did anything wrong. I just wouldn't recommend to "blindly" run `fd … -x sudo rm` :smile:. WE would like to know what went wrong so that we can fix it (if it is indeed a bug). I can not really see how this could have removed all of your files, so I need a way to reproduce it for myself (in a safe environment).



> I'd also like to know for folders requiring root access how to safely batch remove files as non-root user?

I would probably recommend the method above. Use `fd` to create a list of files, review it, then remove all files.

**Comment by ixzh** [comment] 2021-06-10 14:35
>  I can not really see how this could have removed all of your files

last time I exceuted the command like 20+seconds until the system was damaged that could not reboot.. this time I stopped it like 2 seconds after execution... still have the system running..

thank you for the detailed answer. I don't have vm yet 😃

**Comment by sharkdp** [comment] 2021-08-08 09:46
Closing this for now as we can not reproduce it.

**Closed by sharkdp** 2021-08-08 09:46 UTC
Labels: question
