### ISSUE TITLE
Progress bar with --exec command?

### ISSUE THREAD

**Issue by danielkrajnik** [sharkdp/fd#1319] opened 2023-05-21 11:23 UTC
**What version of `fd` are you using?**
`
fd 8.7.0
`

I'm wondering if we could add a "progress bar"  to --exec and --exec-batch commands?

for example: `fd -e png --exec rm` 

Right now there is no output at all, which makes sense, but on long running commands it would be useful. Even better if it reported which file is being processed at any given time.

**Comment by tmccombs** [comment] 2023-05-21 18:29
Duplicate of #740

**Closed by tmccombs** 2023-05-21 18:29 UTC
Labels: question
