### ISSUE TITLE
Does not compile on Windows Powershell

### ISSUE THREAD

**Issue by hherman1** [sharkdp/fd#79] opened 2017-10-08 20:56 UTC
`cargo install fd-find`
```
error: no method named `split_off` found for type `std::string::String` in the current scope
   --> .cargo\registry\src\github.com-1ecc6299db9ec823\fd-find-4.0.0\src\lscolors/mod.rs:136:63
    |
136 |                         let extension = String::from(pattern).split_off(2);
    |                                                               ^^^^^^^^^
```

**Comment by sharkdp** [comment] 2017-10-08 21:13
Which version of `rustc` are you using? You will need at least 1.16

(I guess this is a duplicate of #43)

**Closed** 2017-10-08 21:52 UTC
