### ISSUE TITLE
allocation heavy and get killed by OS

### ISSUE THREAD

**Issue by Martinits** [sharkdp/fd#1063] opened 2022-07-13 09:09 UTC
Just run `fd` in `/` and it keeps allocating memory until OOM and gets killed. I often ran fd under `/` (actually through `fzf` for finding things under `/`). It wasn't like that before.
I'm using fd on archlinux, on a laptop with i7-8550U and 16G RAM.
```
❯ yay -Q fd
fd 8.4.0-1
```

**Comment by tavianator** [comment] 2022-07-13 14:15
Dupe of https://github.com/sharkdp/fd/issues/918 probably

**Closed as not planned by tavianator** 2022-07-13 14:15 UTC
Labels: question

**Comment by tavianator** [comment] 2022-07-13 14:53
It's likely that https://github.com/sharkdp/fd/pull/812/commits/813a802b2cf63c87469ef250dae81f71a8641de3 exacerbated this by increasing the size of the objects passed through the channel.

**Comment by Martinits** [comment] 2022-07-13 14:53
> You can try my [backpressure](https://github.com/tavianator/fd/tree/backpressure) branch. If it still OOMs then it's a different bug, otherwise it's probably the same one.

Just tried this one, it's good.
