### ISSUE TITLE
implement find syntax

### ISSUE THREAD

**Issue by xenoterracide** [sharkdp/fd#1111] opened 2022-09-12 17:14 UTC
would it be possible to implement the posix find interface? I would be ok if it only worked as aliased to `find`? I have trouble using fd because I can never remember the syntax, always have to `man fd`.

mostly I use `find . -name 'glob' -exec command '{}' +` if that makes this simpler

**Comment by xenoterracide** [comment] 2022-09-12 21:01
I mean, I would assume it's simply a context switch based on name and that fd logic around parameter parsing is very light and simply delegates to other things. if there's a ton of "business" logic in argument parsing that seems like a bad idea.

**Comment by xenoterracide** [comment] 2022-09-12 21:04
without this, it's very hard to use fd, not just from a personal perspective, but it can't be taken advantage of in shared scripts because you can't guarantee it's presence.

**Comment by tmccombs** [comment] 2022-09-12 21:28
It isn't just a matter of setting up aliases for option names. Find uses a very different paradigm for options than fd.  For example, find uses a single hyphen before long options, but fd uses two hyphens.  The library we use (clap) doesn't currently support single hyphen long options.  And even if it did, or we switched to a different library , it would introduce ambiguity between long options and short options.

And there are also differences in semantics of some options, and in find order of options matters a whole lot more than in fd. 

The simplest way to implement this in fd itself would probably be to create an entirely different flow for parsing find compatible options that is somehow turned on by another flag or maybe an environment variable.

**Comment by xenoterracide** [comment] 2022-09-12 21:45
Sure that's why I was suggesting that you look at the application name and then switch purses based on the application name I believe that should be argument 0. This is how busybox is a single binary.

**Comment by xenoterracide** [comment] 2022-09-13 18:52
perhaps there could be a compromise in being able to write `fd . --name '*.txt' --exec grep caleb '{}' +` ? at least then it can be invoked similarly, although not scripted.

**Comment by tavianator** [comment] 2022-09-14 20:49
I think this is a duplicate of https://github.com/sharkdp/fd/issues/852.  As I [mentioned](https://github.com/sharkdp/fd/issues/852#issuecomment-919350224) there, the `find` command line is [difficult](https://github.com/tavianator/bfs/blob/main/src/parse.c) to parse, and even more difficult to automatically convert to `fd`'s syntax, since `fd` doesn't support arbitrary boolean expressions.

**Closed** 2022-09-14 20:49 UTC
Labels: feature-request
