### ISSUE TITLE
Can finding by ext in a directory be simpler?

### ISSUE THREAD

**Issue by ououmania** [sharkdp/fd#564] opened 2020-04-11 09:50 UTC
It's simple to find by ext in the current directory. Just type "fd -e ext"
But it's not that simple when I need to find by ext in a directory other than the current one.
"fd -e ext dir" doesn't work, but "fd -e ext '' dir'' does. Is this design on purpose?
It should be unnecessary to specify a pattern because the ext is actually the one.
Any help is appreciable.
![image](https://user-images.githubusercontent.com/45710068/79040692-cbe60780-7c1c-11ea-8485-322c89afd4a4.png)

**Comment by sharkdp** [comment] 2020-04-11 12:50
Duplicate of #312?

**Closed** 2020-04-15 13:40 UTC
Labels: duplicate
