### ISSUE TITLE
How to search for multiple terms?

### ISSUE THREAD

**Issue by ClementNerma** [sharkdp/fd#910] opened 2021-12-23 13:45 UTC
Hi there!

I'm currently looking for a way to search for multiple terms at once, e.g. search for two distinct words (not consecutive) inside filenames. Is that possible? I didn't find anything with `--help` but I may have missed something.

I'm using `fd 8.3.0`.

Thanks in advance for your help :)

**Comment by tmccombs** [comment] 2021-12-24 07:59
Duplicate of #315

**Closed by tmccombs** 2021-12-24 07:59 UTC
Labels: question
