### ISSUE TITLE
wrong 'absolute path' in root (-a flag)

### ISSUE THREAD

**Issue by Remiol** [sharkdp/fd#947] opened 2022-01-25 11:46 UTC
fd 8.3.1
windows 10

The '-a' flag doesn't work in root (in windows).

If I use the '-a' flag from a sub directory fd returns:
d:\my_directory\file1.ext
d:\my_directory\file2.ext

If I use it in root fd returns
d:my_directory\file1.ext
d:my_directory\file2.ext

**Comment by tavianator** [comment] 2022-01-25 14:42
I think this is a duplicate of https://github.com/sharkdp/fd/issues/931, which is already fixed but not yet released.   Thanks for the report!

**Closed** 2022-01-29 15:44 UTC
Labels: duplicate

**Comment by sharkdp** [comment] 2022-01-29 15:58
Fix released as https://github.com/sharkdp/fd/releases/tag/v8.3.2
