### ISSUE TITLE
Global absolute paths in ignore file?

### ISSUE THREAD

**Issue by tjex** [sharkdp/fd#1150] opened 2022-10-29 10:33 UTC
**What version of `fd` are you using?**
8.4.0

I'm setting up the `ignore` file in `.config/fd/`. 
I want to exclude a specific folder that is in my home directory. 
My experience so far is that the dir paths set in `ignore` are relative to where `fd` is being executed. 

Is there then a way to exclude a specific folder, no matter how many levels above the folder I am? 
Ideally it would be great to set `/Users/tillman/foo/` or `~/foo/` in the `ignore` file and have that file excluded no matter where I am in my machine. 

Or is the only way to set:
```
tillman/foo/
/Users/tillman/foo/
etc
```

**Comment by tmccombs** [comment] 2022-11-25 08:01
I don't believe there is currently a way to do that, although I do think the ability to do so would be valuable. 

Too potential hurdles are

1. What should the syntax be? The most straightforward way would be to treat rules starting with / to be absolute instead of relative to the run directory. But that would definitely be backwards incompatible, and I'm not entirely sure how that would work on windows.
2. I'm pretty sure this would require a change to the upstream ignore crate (also used by ripgrep) or at least some creative design to work around how it handles global ignore files (perhaps this issue would be better resolved upstream?)

**Comment by tjex** [comment] 2022-12-03 13:01
I'm not yet knowledgeable enough to have much valuable input... But perhaps there could be an integration with the global gitignore file. Or a check how many levels deep fd is being executed from, and then referencing all ignore paths, but taking into consideration only the ignore paths that are deeper than it's current position in the system (as those would then be the only valid ones)...

Probably a lot wrong with those suggestions, but didn't want to just thow my hands up with no ideas...

**Comment by tmccombs** [comment] 2022-12-05 08:23
First of all, would putting an `.fdignore` file in your home directory specified the given subdirectory should be ignored be an option?

Secondly, from https://github.com/sharkdp/fd/issues/763#issuecomment-894705447, I suspect that if you passed `--absolute-path` then the absolute patterns would work. That is due to some, uh, unexpected behavior of the `ignore` library though.

Finally, for parsing ignore files, and the logic for determining which files to ignore, `fd` uses a third party library called `ignore` (which is also used by ripgrep). You suggestions don't really get around the fact that that library doesn't support absolute path matching, so we would need to do one of the following: get a change merged into the upstream project (see https://github.com/BurntSushi/ripgrep/issues/2366), fork the project and make a change, replace the library with something else, or find some creative way to work around the limitations of the library. 

There might be a way to do that last one. Since, it seems to work if you pass `--absolute-path`, maybe if we always passed in the absolute path for the search path, and then made it relative again when displaying it, it could work. But, and it's a big but, I suspect this could have some unintended side effects, and would be surprised if it didn't hurt performance.

**Comment by tjex** [comment] 2022-12-12 11:24
having the `.fdignore` file in my home directory is a fine solution for me. Thanks for the idea. I didn't realise that the `.fdignore` file could be placed (seemingly) anywhere. I thought it was expected to be in `.config/fd`

**Closed** 2022-12-12 11:48 UTC
Labels: question
