### ISSUE TITLE
Cannot build for Android arm64: undefined reference to getgrnam_r

### ISSUE THREAD

**Issue by kheaactua** [sharkdp/fd#642] opened 2020-08-21 21:07 UTC
**Describe the bug you encountered:**

Cannot build for aarch64-linux-android21-clang with cargo-ndk

**Describe what you expected to happen:**

Building

**What version of `fd` are you using?**
v8.1.1

**Which operating system / distribution are you on?**

Host: `Linux sync-android 5.3.0-62-generic #56-Ubuntu SMP Tue Jun 23 11:20:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
Target:  `aarch64-linux-android21-clang`

Build command:
```
cargo ndk --platform 21 --target aarch64-linux-android install fd-find
```

Error:
```
...
   Compiling jemallocator v0.3.2
   Compiling fd-find v8.1.1
error: linking with `/opt/android-sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang` failed: exit code: 1
  |
  = note: "/opt/android-sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-Wl,--allow-multiple-definition" "-L" "/home/developer/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-linux-android/lib" "/opt/android-src/rust/aarch64-linux-android/release/deps/fd-6573bade394bd70e.fd.7ri3gj1e-cgu.0.rcgu.o" "-o" "/opt/android-src/rust/aarch64-linux-android/release/deps/fd-6573bade394bd70e" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/opt/android-src/rust/aarch64-linux-android/release/deps" "-L" "/opt/android-src/rust/release/deps" "-L" "/opt/android-src/rust/aarch64-linux-android/release/build/jemalloc-sys-2f774dbc453583dc/out/build/lib" "-L" "/home/developer/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-linux-android/lib" "-Wl,-Bstatic" "/tmp/rustcfutFGu/libjemalloc_sys-472fec3e55f702f0.rlib" "-Wl,--start-group" "/tmp/rustcfutFGu/libbacktrace_sys-0cef47a6ea2f6faa.rlib" "-Wl,--end-group" "/home/developer/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-linux-android/lib/libcompiler_builtins-4e815dabfb033b9c.rlib" "-Wl,-Bdynamic" "-lgcc" "-ldl" "-llog" "-lgcc" "-lc" "-lm"
  = note: /opt/android-src/rust/aarch64-linux-android/release/deps/fd-6573bade394bd70e.fd.7ri3gj1e-cgu.0.rcgu.o: In function `fd::run::heead038217ac7ff2':
          fd.7ri3gj1e-cgu.0:(.text._ZN2fd3run17heead038217ac7ff2E+0x567c): undefined reference to `getgrnam_r'
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: aborting due to previous error

error: failed to compile `fd-find v8.1.1`, intermediate artifacts can be found at `/opt/android-src/rust/`

Caused by:
  could not compile `fd-find`.
```

**Comment by sharkdp** [comment] 2020-09-01 21:44
Same as #636?

**Comment by kheaactua** [comment] 2020-09-02 10:08
Not exactly..  It looks like the build is for termux in #636 , while mine is with the NDK, and the missing symbols are different.  I suppose it's the same as in they're both for Android arm64.

**Comment by sharkdp** [comment] 2020-10-05 18:10
Ok. Thanks.

I'm probably not going to work on this myself, as I don't really have a way to test it. If it's related to jemalloc, that can be deactivated.

**Comment by kheaactua** [comment] 2020-10-06 00:20
How?

**Comment by sharkdp** [comment] 2020-10-06 04:55
Either apply this patch:
``` patch
diff --git a/Cargo.lock b/Cargo.lock
index 5d234cb..1dcfcb5 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -171,7 +171,6 @@ dependencies = [
  "globset 0.4.5 (registry+https://github.com/rust-lang/crates.io-index)",
  "humantime 2.0.0 (registry+https://github.com/rust-lang/crates.io-index)",
  "ignore 0.4.15 (registry+https://github.com/rust-lang/crates.io-index)",
- "jemallocator 0.3.2 (registry+https://github.com/rust-lang/crates.io-index)",
  "lazy_static 1.4.0 (registry+https://github.com/rust-lang/crates.io-index)",
  "libc 0.2.70 (registry+https://github.com/rust-lang/crates.io-index)",
  "lscolors 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)",
@@ -199,11 +198,6 @@ name = "fnv"
 version = "1.0.7"
 source = "registry+https://github.com/rust-lang/crates.io-index"
 
-[[package]]
-name = "fs_extra"
-version = "1.1.0"
-source = "registry+https://github.com/rust-lang/crates.io-index"
-
 [[package]]
 name = "fuchsia-cprng"
 version = "0.1.1"
@@ -261,25 +255,6 @@ dependencies = [
  "winapi-util 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)",
 ]
 
-[[package]]
-name = "jemalloc-sys"
-version = "0.3.2"
-source = "registry+https://github.com/rust-lang/crates.io-index"
-dependencies = [
- "cc 1.0.53 (registry+https://github.com/rust-lang/crates.io-index)",
- "fs_extra 1.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
- "libc 0.2.70 (registry+https://github.com/rust-lang/crates.io-index)",
-]
-
-[[package]]
-name = "jemallocator"
-version = "0.3.2"
-source = "registry+https://github.com/rust-lang/crates.io-index"
-dependencies = [
- "jemalloc-sys 0.3.2 (registry+https://github.com/rust-lang/crates.io-index)",
- "libc 0.2.70 (registry+https://github.com/rust-lang/crates.io-index)",
-]
-
 [[package]]
 name = "lazy_static"
 version = "1.4.0"
@@ -558,15 +533,12 @@ source = "registry+https://github.com/rust-lang/crates.io-index"
 "checksum dirs-sys 0.3.4 (registry+https://github.com/rust-lang/crates.io-index)" = "afa0b23de8fd801745c471deffa6e12d248f962c9fd4b4c33787b055599bde7b"
 "checksum filetime 0.2.10 (registry+https://github.com/rust-lang/crates.io-index)" = "affc17579b132fc2461adf7c575cc6e8b134ebca52c51f5411388965227dc695"
 "checksum fnv 1.0.7 (registry+https://github.com/rust-lang/crates.io-index)" = "3f9eec918d3f24069decb9af1554cad7c880e2da24a9afd88aca000531ab82c1"
-"checksum fs_extra 1.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = "5f2a4a2034423744d2cc7ca2068453168dcdb82c438419e639a26bd87839c674"
 "checksum fuchsia-cprng 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = "a06f77d526c1a601b7c4cdd98f54b5eaabffc14d5f2f0296febdc7f357c6d3ba"
 "checksum getrandom 0.1.14 (registry+https://github.com/rust-lang/crates.io-index)" = "7abc8dd8451921606d809ba32e95b6111925cd2906060d2dcc29c070220503eb"
 "checksum globset 0.4.5 (registry+https://github.com/rust-lang/crates.io-index)" = "7ad1da430bd7281dde2576f44c84cc3f0f7b475e7202cd503042dff01a8c8120"
 "checksum hermit-abi 0.1.13 (registry+https://github.com/rust-lang/crates.io-index)" = "91780f809e750b0a89f5544be56617ff6b1227ee485bcb06ebe10cdf89bd3b71"
 "checksum humantime 2.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = "b9b6c53306532d3c8e8087b44e6580e10db51a023cf9b433cea2ac38066b92da"
 "checksum ignore 0.4.15 (registry+https://github.com/rust-lang/crates.io-index)" = "128b9e89d15a3faa642ee164c998fd4fae3d89d054463cddb2c25a7baad3a352"
-"checksum jemalloc-sys 0.3.2 (registry+https://github.com/rust-lang/crates.io-index)" = "0d3b9f3f5c9b31aa0f5ed3260385ac205db665baa41d49bb8338008ae94ede45"
-"checksum jemallocator 0.3.2 (registry+https://github.com/rust-lang/crates.io-index)" = "43ae63fcfc45e99ab3d1b29a46782ad679e98436c3169d15a167a1108a724b69"
 "checksum lazy_static 1.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = "e2abad23fbc42b3700f2f279844dc832adb2b2eb069b2df918f455c4e18cc646"
 "checksum libc 0.2.70 (registry+https://github.com/rust-lang/crates.io-index)" = "3baa92041a6fec78c687fa0cc2b3fae8884f743d672cf551bed1d6dac6988d0f"
 "checksum log 0.4.8 (registry+https://github.com/rust-lang/crates.io-index)" = "14b6052be84e6b71ab17edffc2eeabf5c2c3ae1fdb464aae35ac50c67a44e1f7"
diff --git a/Cargo.toml b/Cargo.toml
index 2c052fe..d9342d2 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -58,12 +58,6 @@ users = "0.10.0"
 [target.'cfg(all(unix, not(target_os = "redox")))'.dependencies]
 libc = "0.2"
 
-# FIXME: Re-enable jemalloc on macOS
-# jemalloc is currently disabled on macOS due to a bug in jemalloc in combination with macOS
-# Catalina. See https://github.com/sharkdp/fd/issues/498 for details.
-[target.'cfg(all(not(windows), not(target_os = "macos"), not(target_env = "musl")))'.dependencies]
-jemallocator = "0.3.0"
-
 [dev-dependencies]
 diff = "0.1"
 tempdir = "0.3"
diff --git a/src/main.rs b/src/main.rs
index 4c95f06..5c12c58 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -32,12 +32,6 @@ use crate::filter::{SizeFilter, TimeFilter};
 use crate::options::Options;
 use crate::regex_helper::pattern_has_uppercase_char;
 
-// We use jemalloc for performance reasons, see https://github.com/sharkdp/fd/pull/481
-// FIXME: re-enable jemalloc on macOS, see comment in Cargo.toml file for more infos
-#[cfg(all(not(windows), not(target_os = "macos"), not(target_env = "musl")))]
-#[global_allocator]
-static ALLOC: jemallocator::Jemalloc = jemallocator::Jemalloc;
-
 fn run() -> Result<ExitCode> {
     let matches = app::build_app().get_matches_from(env::args_os());
 ```

Or make sure that your [target triple](https://doc.rust-lang.org/nightly/rustc/platform-support.html) is properly excluded (like macOS).

**Comment by sharkdp** [comment] 2020-10-08 10:47
@matu3ba It would be great to get some feedback if the bug is fixed on `master`, thanks to the change by @fornwall.

**Closed by sharkdp** 2020-10-08 10:47 UTC
Labels: bug, help wanted

**Comment by vfsfitvnm** [comment] 2021-03-15 09:47
Hi. 
This is not a problem with `jemalloc`.
In fact, after applying the patch, the error remains:
```In function `users::base::get_group_by_name::hdeff5d973b39c900':
          /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/users-0.11.0/src/base.rs:513: undefined reference to `getgrnam_r'```

The problem is with the default android linker:
``` 
// .cargo/config
[target.aarch64-linux-android]
ar = "/home/xxx/.NDK/arm64/bin/aarch64-linux-android-ar"
linker = "/home/xxx/.NDK/arm64/bin/aarch64-linux-android-clang"
```
`aarch64-linux-android-clang` must be replaced with `aarch64-linux-android24-clang`, because `getgrnam_r` [was added in API 24](https://github.com/rust-lang/libc/issues/1765#issuecomment-709654843), so it cannot be build for android platforms < 24.

After that, I could make `cargo build --target aarch64-linux-android --release` to work.

**Comment by sharkdp** [comment] 2021-05-16 19:58
@vfsfitvnm Thank you for the information!
