### ISSUE TITLE
Exec fails in Powershell when providing .bat command

### ISSUE THREAD

**Issue by bagage** [sharkdp/fd#585] opened 2020-05-07 14:09 UTC
**Describe the bug you encountered:**
I saw multiple issues relative to exec `-x` issues on windows and/or powershell. (#538, #310 mainly).

When I try to execute a `.bat` script that is available in `$PATH`, `fd` raises an error:

```sh
$ fd -e php -x php-cs-fixer.bat fix
Could not open input file: D:\currentFolder\/../friendsofphp/php-cs-fixer/php-cs-fixer
```

The file is located at `C:\Users\user\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.bat` and available in `$PATH`.

The same command with absolute path works as expected:

```sh
$ fd -e php -x C:\Users\user\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.bat fix
...
Fixed all files in 0.004 seconds, 12.000 MB memory used
...
```

**Describe what you expected to happen:**

I'd expect both versions to work since the bat is available through `$PATH`.

**What version of `fd` are you using?**

fd 7.5.0 (version 8.0.0 seems broken, garbage characters are being displayed on output).

**Which operating system / distribution are you on?**

Using Windows 7 and pwsh 7.0.0.

**Comment by sharkdp** [comment] 2020-05-12 20:24
Thank you for reporting this. That looks like a bug indeed.

Will probably require help from someone with a Windows machine to test on.

> version 8.0.0 seems broken, garbage characters are being displayed on output

Oh. Could this be #577?

**Comment by bagage** [comment] 2020-05-13 08:30
Yes indeed this is #577 (using pwsh under W7).

I'd be happy to help fixing this issue - just need some instructions here :).

**Comment by sharkdp** [comment] 2020-05-19 12:19
I can not reproduce this:

![image](https://user-images.githubusercontent.com/4209276/82325579-c0d08500-99db-11ea-9424-dc24982a0424.png)

**Comment by sharkdp** [comment] 2020-05-24 12:48
@bagage It would be great if you could post a reproducible test case here.

**Comment by bagage** [comment] 2020-05-25 07:13
@sharkdp your scenario does indeed work for me too; but it does not work with `php-cs-fixer.bat`.

Actually, I found out that this is not `fd` that cannot find the executable, but within the script:

1. Modify `test.bat` to contain ècho %~dp0` (equivalent of `$0`, [see explanation](https://stackoverflow.com/questions/5034076/what-does-dp0-mean-and-how-does-it-work))
2. `cd D:\ && test.bat` echoes `C:\Users\IEUser\test`
3. `cd D:\ && fd test -x test.bat`  echoes `C:\Users\IEUser\test`, or basically **current working directory** instead of **script directory**. Since php script relies on it to find its files, it causes 404 not found error.

**Comment by sharkdp** [comment] 2020-05-25 09:50
ok.. so this is not a bug in `fd`? Can this be closed then?

**Comment by bagage** [comment] 2020-05-25 11:43
Well I believe the bug is within `fd`, because somehow when an executable is invoked via `fd` it doesn't have proper environment variables?

**Comment by sharkdp** [comment] 2020-05-25 13:28
Ok, I can reproduce this.

This seems to be some weird behavior of Bat scripts or `cmd.exe`. See for example:
- https://stackoverflow.com/questions/12141482/what-is-the-reason-for-batch-file-path-referenced-with-dp0-sometimes-changes-o
- https://stackoverflow.com/questions/58607958/dp0-returns-incorrect-path

You can circumvent this by using:
```
fd … -x cmd /c test.bat
```
to make sure it's running inside a shell. We *could* do this by default in `fd`, but we decided against this. We don't want to launch intermediate shells, mainly for performance reasons.

**Comment by sharkdp** [comment] 2020-06-07 14:00
I'm closing this for now, as I don't know what else to do. Feedback would be great.

**Closed by sharkdp** 2020-06-07 14:00 UTC
Labels: bug, windows
