### ISSUE TITLE
Extend filetype-filtering to include named pipes and sockets like POSIX find

### ISSUE THREAD

**Issue by Seirdy** [sharkdp/fd#549] opened 2020-03-17 05:09 UTC
POSIX [`find(1)`](https://www.unix.com/man-page/posix/1P/find/) allows using the
`-type` option to filter to named pipes (FIFO) and sockets. `fd` would be better able
to replace the POSIX find utility if it could also filter these filetypes.

**Comment by tmccombs** [comment] 2020-03-17 05:51
Duplicate of #511?

**Closed** 2020-03-17 21:46 UTC
Labels: duplicate
