### ISSUE TITLE
fd is too eager to escape arguments under Windows

### ISSUE THREAD

**Issue by mqudsi** [sharkdp/fd#299] opened 2018-05-17 01:44 UTC
This one is a bit tricky: under Windows/cmd `"C:\Program Files\dotnet\"<ENTER>` does *not* evaluate to `C:\Program Files"` (as fd currently thinks it does).

cmd escaping is convoluted, especially compared to the simplicity of unix escaping. What's more, quotes are implicitly closed on enter, and may appear anywhere in the term.

The following all evaluate to `C:\Program Files` or `C:\Program Files\`

* `"C:\Program Files"`
* `"C:\Program Files\"`
* `C:\Program" Files"`
* `C:\Progra"m Files"`
* `C:\"Program Files`

A literal `"` may be obtained only by opening and closing a non-literal "group" (pair) of double-quotes (whether you need them or not), and directly following that up with another `"` which will be taken literally.

Remember what I said above about quotes being closed implicitly: `foo"` is equivalent to `foo""` which as we saw is just `foo` concatenated with an empty string (enclosed in double-quotes, the latter of which was implicitly added). 

So you _need_ to be using string-delimiting double quotes (not literal double quotes) already, and follow them up *immediately* (without spaces) with another double quote to get a literal double quotation mark output. The easiest way to do that _if you're not already in a double-quoted string_ is to just open and close an empty string, and follow that up with a literal quote, which leads people to misunderstand that and assume three quotes is how a literal quote is emitted.

To make matters more complicated, there are multiple levels of quote parsing and argument tokenization at play in the Windows command line. The shell interpreter itself (`cmd.exe`) performs one level of tokenization, and the CRT (the Windows equivalent of libc) performs another on the arguments it receives from the kernel, and passes them along to your `main()` method.

I'm not sure how much of that is done automatically for rust programs, but `GetCommandLineW` can be used to retrieve the literal string the command was executed with (untokenized), after which `CommandLineToArgvW()` can be used to tokenize it.

**Comment by sharkdp** [comment] 2018-05-17 06:25
Thank you for your feedback.

How is this bug triggered? Where does `fd` perform any escaping?

We used to launch a sub-shell when using `--exec` but opted out due to problems with shell escaping.

**Comment by mqudsi** [comment] 2018-05-17 07:11
Sorry; I should have mentioned instead of just implying it affected paths. One runs into it pretty quickly as it reproduces with the most basic `fd foo “hello\world\”`

(Sorry for the typographic quotes. On iOS.)

**Comment by mqudsi** [comment] 2018-07-02 22:44
I just got around to testing this now.

```powershell
PS C:\Users\Mahmoud> fd .*\.ase "C:\Program Files\"
Error: 'C:\Program Files"' is not a directory.
```

(notice the extra `"` at the end of the path in the error message)

But it's weird because it *did* treat it as a quote as all of `Program Files` was treated as one word (with an additional `"` at the end), which wouldn't happen if the character _weren't_ recognized as a quoting grammar token:

Additionally, look at this:

```powershell
PS C:\Users\Mahmoud> fd .*\.ase 'C:\Program Files\'
Error: 'C:\Program Files"' is not a directory.
```

I'm not sure why but a literal `"` is included in the path here, even though no such symbol actually appears in the text as entered.

**Comment by sharkdp** [comment] 2018-07-05 19:14
If quotes are closed implicitly (as you stated above), isn't that exactly the expected behavior?

I would expect
```
fd .*\.ase "C:\Program Files\"
```
to be implicitly equal to
```
fd .*\.ase "C:\Program Files\""
```
because the other quote is escaped. For `fd`, the argument would look like `C:\Program Files"`. This is why it reports:
```
Error: 'C:\Program Files"' is not a directory.
```

**Comment by stevepentland** [comment] 2018-08-31 01:44
@sharkdp this could be because in powershell (which it looks like from the 'PS' prefix on the examples) the escape character is not \ but is rather the backtick ` character. Mostly due to windows path differences and using the \ character in them, so \" is literally \"

**Comment by sharkdp** [comment] 2018-10-27 12:49
I'm going to close this, as it's not clear to me if this is a bug.

**Closed by sharkdp** 2018-10-27 12:49 UTC
Labels: help wanted
